language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
directories:
- node_modules
notifications:
email: false
branches:
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
install:
  - npm ci
script:
  - npm test
